### ISSUE TITLE
Finalize TEC website design

### ISSUE THREAD

**Issue by jessicazartler** [TECommons/coordination#1]
## 📋   Anything to add?
https://tecommons.org/

## 🎉   Subtasks

- [x] Jess and Blair write content
- [x] Kay set up back end with Manu
- [x] Rosa set up wordpress instance
- [x] Marko polish design
- [ ] Jess and Blair edit content
- [ ] Marko and Manu work on front end design
- [ ] Jess and Blair tweak layout and content
- [ ] Manu finazlize front end
- [ ] Launch & promo

## 🤼‍♂️   Reviewer

@jessicazartler @bvanderlugt 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1VOM39PVE41_GYKUbdZCZIu_xySDp60tLTXqup2-t27I/edit

**Comment by jessicazartler** [comment]
This also should probably be an epic ayyyy need to break down into issues @tamarandom

**Comment by tamarandom** [comment]
🙏🏼 another to review in our working session together.
