### ISSUE TITLE
Make Forum posts for debating the Dandelion Parameters #96

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#101]
## 📋 Anything to add?

Here is what we had fro the first trial: 

// Used for administrative or binary choice decisions with ragequit-like functionality
const SUPPORT_REQUIRED = 0.6 * ONE_HUNDRED_PERCENT
const MIN_ACCEPTANCE_QUORUM = 0.02 * ONE_HUNDRED_PERCENT
const VOTE_DURATION_BLOCKS = 3 * DAYS / BLOCKTIME
const VOTE_BUFFER_BLOCKS = 8 * HOURS / BLOCKTIME
const VOTE_EXECUTION_DELAY_BLOCKS = 24 * HOURS / BLOCKTIME
const TOLLGATE_FEE = 3 * ONE_TOKEN

## ⏰ Urgency/Due Date/Blockers?

Needs to get done this sprint!

## ❓ Why is it important?

Gives power to the people!

## 🎉 Subtasks

- [x] make main post
- [x] find champions for the other posts
- [x] make all the small posts

## 🤼‍ Reviewer

@GriffGreen 

## 🔗 Work doc - inspirational links

Hatch Thread: https://forum.tecommons.org/t/test-hatch-1-rinkeby-deployment-hatch-discussion-thread/61

Parameters for CV are here: https://github.com/TECommons/tec-template/blob/master/scripts/new-dao.js

**Comment by LinuxIsCool** [comment]
All of the discussions are here: 

https://forum.tecommons.org/c/Token-talk-anything-about-the-TEC-token-such-as-issuance-and-hatches/9
