### ISSUE TITLE
Hatch improvements

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#111]
## 📋 Anything to add?

More details can be found on the project board for Garden Swarm here:

https://github.com/orgs/TECommons/projects/1

## 🎉 Subtasks
See more at : https://github.com/orgs/TECommons/projects/1

- [ ] Min and max goals 
- [ ] Impact hours conversion
- [ ] Limiting contributions based on CSTK

## 🤼‍ Reviewer

@

**Comment by iviangita** [comment]
Copied and moved to Gardens Swarm Workspace [issue 25](https://app.zenhub.com/workspaces/garden-swarm-workspace-5fe322aef3aab0001be1d518/issues/tecommons/tec-ui/25)
