### ISSUE TITLE
Setup Forum

### ISSUE THREAD

**Issue by jessicazartler** [TECommons/coordination#12]
## 📋   Anything to add?
https://forum.tecommons.org/
## 🎉   Subtasks

- [x] Kay setup back end
- [x] Blair & Jess review examples 
- [x] Jess setup categories
- [x] polish about sections and see if we need anything further

## 🤼‍♂️   Reviewer

@GriffGreen @jessicazartler

**Comment by jessicazartler** [comment]
https://forum.tecommons.org/

Could mayyybe use more polishing but I'ma close it and consider it done :D
