### ISSUE TITLE
Setup YouTube

### ISSUE THREAD

**Issue by jessicazartler** [TECommons/Coordination#13]
## 📋   Anything to add?
https://www.youtube.com/channel/UCagCOhMqMNU29rWx259-tcg
## 🎉   Subtasks

- [x] Jess create channel, tags, default options
- [x] Jess work with Zeptimus/Ivy to upload videos & polish descriptions
- [x] Share with community & Tweet

## 🤼‍♂️   Reviewer

@GriffGreen @jessicazartler

**Comment by jessicazartler** [comment]
Eh voila! https://www.youtube.com/channel/UCagCOhMqMNU29rWx259-tcg
Follow like and subscribe!

**Comment by jessicazartler** [comment]
@GriffGreen finished! 
https://www.youtube.com/channel/UCagCOhMqMNU29rWx259-tcg

**Comment by jessicazartler** [comment]
Yay!
