### ISSUE TITLE
Automated Options for Onboarding & Rewards Systems Documentation

### ISSUE THREAD

**Issue by jessicazartler** [TECommons/coordination#14]
## 📋   Anything to add?
*Can move this task to Soft Gov when their Github work board is up

## 🎉   Subtasks

- [x] Jess document options from other DAOs (1Hive examples)
- [x] Livia Review & Pass to Soft Gov group for feedback & discussion
- [x] Integrate feedback into initial proposal (Jess/Livi/volunteers)

## 🤼‍♂️   Reviewer

@liviade1 @GriffGreen 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/16fZG4QJycKDTGrJAKWT-caflBE3g53o1L2k64ztIlZM/edit?userstoinvite=liviaieaou%40gmail.com&ts=5f9a0367&actionButton=1
