### ISSUE TITLE
Manage the first TEC test Deployment!

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#15]
## 📋   Anything to add?

The Devil is in the Details :-D The action is here: https://github.com/orgs/TECommons/projects/1

## 🎉   Subtasks

- [x]  Talk about this in the Community Stewards call!!! 
- [x] Add issues/notes continuously to the Project board here: https://github.com/orgs/TECommons/projects/1
- [x] Keep it up to date every week!

## 🤼‍♂️   Reviewer

@GriffGreen 

## 🔗   Work doc - inspirational links
https://github.com/orgs/TECommons/projects/1

**Comment by tamarandom** [comment]
Closing. Sem is all done with this.
