### ISSUE TITLE
Onboarding WG manage communications with the CSTK holders list 

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#152]
## 📋   Anything to add?

Craig has the CSTK token holder list. 

## 🎉   Subtasks

- [ ] Craig, can you add the list to this issue, please. 
- [x] Sync on past communications (Craig/Eduardo)
- [x] Split list into groups to be assigned to WG contributors
- [ ] Craft comms
- [ ] Plan/process to keep communication channels open ongoing

## 🤼‍♂️   Reviewer

@

**Comment by cranders1** [comment]
The CSTK holders list is a Commons Stack product. While I have access, @GriffGreen owner. It has lots of sensitive info. 

I maintain a list of IH holders, some of which have successfully registered for Trusted Seed but don't necessarily have CSTK tokens. I pull updates, also with sensitive info, from Griff's master.

Which is desired, all CSTK or TEC IH?

**Comment by tamarandom** [comment]
@GriffGreen @cranders1 @eduardovegap Is this issue still relevant? If so, what are the next steps to take here?

**Comment by eduardovegap** [comment]
Not anymore, since we are reaching out to people to Onboard them. What IT is relevant, is the process of keeping channels open and going with the people from that list / onboarded ones, but I don't see why the content would be different from any other created comms.

**Comment by cranders1** [comment]
@knobsdao is leading this effort from the CSTK side. Sounds like he is close and the initial email should go out soon.

**Comment by eduardovegap** [comment]
Closing it down, any update, please let us now @cranders1
