### ISSUE TITLE
Hatch Release Plan

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#155]
## 📋 Anything to add?

Critical path to Hatch launch. What does that look like?

## 🎉 Subtasks

- [x] Identification of all activities critical to launch
- [X] Draft Release Plan :  the high level overview of timeline and interdependences 
- [X] Refine with TEC working groups
- [x] Publish to all

## 🤼‍ Reviewer

@

## 🔗 Work doc - inspirational links
[hatch readiness working session 
](https://miro.com/app/board/o9J_lbkGJHQ=/)

**Comment by tamarandom** [comment]
Added "TEC Roadmap to Hatch" to the [Miro board](https://miro.com/app/board/o9J_lbkGJHQ=/). 

 ![Screen Shot 2020-12-16 at 10.38.33 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/8b20108b-70ad-4db2-bf0c-088d6e779fd7)
