### ISSUE TITLE
Launch the 1hive Gardens Swarm

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#16]
## 📋   Anything to add?

This group will have 

## 🎉   Subtasks

- [x] Create an initial DAO proposal
- [x] Get feedback from proposed DAO members
- [x] Deploy DAO
- [x] Create Forum Post
- [x] Integrate feedback from Forum Post
- [x] Propose to 1hive CV
- [x] Get everyone to agree to how we work together (telegram channel with daily work log and hour reporting)
- [x] Get everyone to agree to an hourly wage

## 🤼‍♂️   Reviewer

@sembrestels
