### ISSUE TITLE
TEC Email Newsletter / Outbound Hatch Campaign

### ISSUE THREAD

**Issue by jessicazartler** [TECommons/coordination#163]
## 📋 Anything to add?

We need to build towards an email newsletter / outbound campaign for all of our news/comms

## 🎉 Subtasks

- [ ] Organize all of our TEC member emails into a CSV
- [ ] Decide on platform - Hubspot/Mailchimp/Substack
- [ ] Sign up to platform & import CSV
- [ ] Build campaigns

## 🤼‍ Reviewer

@knobsdao @krisjpi @cranders1

**Comment by tamarandom** [comment]
Closing this Epic! All the issues are closed! Woot!

**Comment by jessicazartler** [comment]
This was a BEAST! Congratulations and great work to @krisjpi @knobsdao @cranders1 for their work on pushing through all the blockers and getting this done!! Thank you guys so much!!
