### ISSUE TITLE
Set up new TEC Discord

### ISSUE THREAD

**Issue by jessicazartler** [TECommons/coordination#167]
## 🎉 Subtasks

- [x] Work session Fri. Dec. 4 9am PST to sync w/ Kris on what he's done so far (Kris/Santi/Dan/Jess/Craig/Livia)
- [x] **COMMS** - Deciding channels/categories (Jess take responsibility - team task) -- Async + feedback round
- [ ] **ONBOARDING** - Designing onboarding journey (Eduardo/Craig/Kris/Jess) -- Kris let us know when he needs feedback
- [ ] **ONBOARDING** - Building out categories with pinned messages & info
- [ ] **TECH** - Implementing spam blocking measures (Kris/Durgadas) -- Async
- [ ] **TECH** - Boosting/making sure we have capacity for call channels (Kris/Tanner)
- [ ] **REWARDS** - Syncing with Rewards WG / Implementing bots (Santi/Mateo/Kris) -- Work session after testing
          BOTS NEEDED: bot for sign up (maybe include email and merge w/ subscribe bot for newsletter Github issue #6 
                                   Do we want to have a faucet?
- [ ] **COMMS** - Planning launch campaign w/ newsletter/medium/forum? + distribution / migrating everyone - sync Angela/Sebnem (Jess/Kris Comms WG)

## 🤼‍ Reviewer

@jessicazartler @krisjpi @Santigs 

## 🔗 Work doc - inspirational links

SOURCE CRED EXPLORER https://tecommons.github.io/tec-sourcecred/#/explorer

BOTS IDEAS & RESOURCE https://docs.google.com/document/d/16fZG4QJycKDTGrJAKWT-caflBE3g53o1L2k64ztIlZM/edit?userstoinvite=liviaieaou%40gmail.com&ts=5f9a0367&actionButton=1

CATEGORIES/CHANNELS
https://docs.google.com/document/d/1Cr_GSoGaW7SfslvIMwtFvoyj1U7i1EWWvtO2Euj7_e4/edit?usp=sharing

**Comment by jessicazartler** [comment]
This needs to be an epic -- @tamarandom would you be able to help me by graduating this to an epic and breaking out all of these tasks into issues? Also some of them may already be represented but are dependencies.. Thank you!

**Comment by tamarandom** [comment]
Sure, @jessicazartler. Let's do it together during our working session.
