### ISSUE TITLE
Blog: Praise Quantification Oct. 24 - Nov. 6

### ISSUE THREAD

**Issue by jessicazartler** [TECommons/coordination#17]
## 🎉   Subtasks

- [x] Jess write draft
- [x] Griff screenshot IHs
- [x] Livia, Griff & stewards review
- [x] Publish 
- [x] Distribute

## 🤼‍♂️   Reviewer

@liviade1 @GriffGreen 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1uQR7bZOoo2CHhimtir-KlEDyIBnPXqnqneM0-4HySxM/edit#

**Comment by jessicazartler** [comment]
https://twitter.com/tecmns/status/1326264493266018304
