### ISSUE TITLE
Make a funding proposal for Gardens Swarm

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#179]
## 📋 Anything to add?

Due to the drop in HNY price, we need to request more funding

## ⏰ Urgency/Due Date/Blockers?

Blocked slightly by wanting to have the Rehearsal hatch First.

## ❓ Why is it important?

Gotta pay da devs

## 🎉 Subtasks

- [ ] Revise https://forum.1hive.org/t/bootstrapping-the-1hive-gardens-swarm-dao/1159 
- [ ] Post it to the forum
- [ ] 3 days later incorporate feed back and propose it to the 1hive's CV

## 🤼‍ Reviewer

@sembrestels

**Comment by GriffGreen** [comment]
We made a lot of improvements in the tech!

**Comment by GriffGreen** [comment]
we adapted the aragon converter

**Comment by GriffGreen** [comment]
https://docs.google.com/document/d/1y2Pgiph3nKOp9xY-Dn6hoJyzgW_qZQ3O6otoKMZRnCU/edit#

**Comment by iviangita** [comment]
Copied and moved to Gardens Swarm Workspace [issue 24](https://app.zenhub.com/workspaces/garden-swarm-workspace-5fe322aef3aab0001be1d518/issues/tecommons/tec-ui/24)
