### ISSUE TITLE
Launch Demo Rehearsal of full test

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#187]
## ⏰ Urgency/Due Date/Blockers?

Tuesday? :-D

## 🎉 Subtasks

- [ ] Decide how to separate the hatch out
- [ ] Finish separating the Hatch from the Marketplace App
- [ ] Add in Impact hours formula to the Hatch 
- [ ] Finishing touches the Hatch app
- [ ] Pass newDAO js to Griff for quick review

## 🤼‍ Reviewer

@GriffGreen
