### ISSUE TITLE
Update the forum to have Onboarding guide and resources 

### ISSUE THREAD

**Issue by liviade1** [TECommons/coordination#19]
## 🎉   Subtasks

- [x] Decide the most important topics 
- [x] Pick a champion for each topic
- [ ] - What is the TEC  (use or improve from the blog post description)- Jess
- [ ] -  How to become a Hatcher - blocked by token dapp
- [ ] - Submit a proposal for funding - Jess
- [ ] -  How to join and contribute - Livia
- [x] - Glossary of terms - Craig
- [x] - How to earn tokens -  Craig and Santi (Santi with the SourceCred side) 
- [ ] Celebrate and promote!

## 🤼‍♂️   Reviewer

@

**Comment by cranders1** [comment]
3 forum drafts to hack on as available, largely scavenged from existing resources:

**How to Earn CSTK Tokens**: waiting CSTK dapp info
[https://docs.google.com/document/d/1ygeQgR7qbc7NiF2wWQFZlKTd3cd66iuM15Nc-8ikgh4/edit?usp=sharing](https://docs.google.com/document/d/1ygeQgR7qbc7NiF2wWQFZlKTd3cd66iuM15Nc-8ikgh4/edit?usp=sharing
)

**How to Earn TEC Tokens**: waiting CSTK dapp linkage
[https://docs.google.com/document/d/1N_G-elHvhTp0mp7yBKJMCoBc3x0FgGwS6xvS4hmzneg/edit?usp=sharing](https://docs.google.com/document/d/1N_G-elHvhTp0mp7yBKJMCoBc3x0FgGwS6xvS4hmzneg/edit?usp=sharing)

**Glossary of Terms**: random scanning of CSTK, TEC, TE, cadcad, etc
[https://docs.google.com/document/d/1A-A0Ws7XMhlpJfDS5G4KbbSEzruuA6vZ2MPB4eJwhW4/edit?usp=sharing](https://docs.google.com/document/d/1A-A0Ws7XMhlpJfDS5G4KbbSEzruuA6vZ2MPB4eJwhW4/edit?usp=sharing)
