### ISSUE TITLE
Create onboarding guide for the legal working group 

### ISSUE THREAD

**Issue by liviade1** [TECommons/coordination#20]
## 🎉   Subtasks

- [ ] What Legal experts need to know about the TEC to participate in the legal wg?
- [ ] Explain Hatch and the bonding curve
- [ ] Explain Trusted Seed 

## 🤼‍♂️   Reviewer

@GriffGreen

**Comment by GriffGreen** [comment]
Added it to the bottom of the legal manifesto!
