### ISSUE TITLE
Implement Ostrom's principles

### ISSUE THREAD

**Issue by iviangita** [TECommons/coordination#216]
## 📋 Anything to add?
Copied from CS repo [issue 211](https://app.zenhub.com/workspaces/commons-stack-workspace-5f1206c0362e7b000fc0161b/issues/commons-stack/iteration0/211) 

## 🎉 Subtasks

- [ ]  principle 1 and 2 - propose a written agreement of our boundaries and rules
- [ ]  principle 3 - experiment the advice process in the forum as part of submitting a proposal
- [ ]  principle 4 - it will come out of the legal working group
- [ ]  principles 5,6,7 - proposal coming out of the conflict management working group
- [ ]  principle 8 - proposal for our fractal configuration

## 🤼‍ Reviewer

@GriffGreen

**Comment by tamarandom** [comment]
@liviade1 These are being covered under separate issues already. Can we close this issue out now? It was a carry-over from the CS repository!

**Comment by tamarandom** [comment]
Hey @liviade1 - Closing!
