### ISSUE TITLE
TEC Hatch Agreements

### ISSUE THREAD

**Issue by iviangita** [TECommons/coordination#217]
## 📋 Anything to add?
Part of Soft Gov agreements

Copied from CS repo [issue 394](https://app.zenhub.com/workspaces/commons-stack-workspace-5f1206c0362e7b000fc0161b/issues/commons-stack/iteration0/394)

## 🎉 Subtasks

- [ ] Make a bullet point list
- [ ] Get it reviewed by Santi
- [ ] Flesh it out into a forum post?

## 🤼‍ Reviewer

@Santigs

**Comment by tamarandom** [comment]
@liviade1 @GriffGreen These are covered in #234 #244 and #253, right? I'll close this now then.

**Comment by GriffGreen** [comment]
:-D probably
Thank you for the clean up @liviade1 ?
