### ISSUE TITLE
Organize resources

### ISSUE THREAD

**Issue by liviade1** [TECommons/coordination#22]
## 🎉   Subtasks

- [ ] separate historical docs from active ones
- [ ] post historical docs on proposal tracking sheet 
- [ ] place active on wiki
- [ ] write a TLDR for each doc on wiki 
- [ ] clean the historical docs from comments/suggestions that date back 
- [ ] place the docs on resources under related sections on the onboarding titles
- [ ] introduce the community stewards 

## 🤼‍♂️   Reviewer

@

**Comment by GriffGreen** [comment]
#19 duplicated?
