### ISSUE TITLE
The TEC Decision making process is missing a couple critical details

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#24]
## 🎉   Subtasks

- [ ] Add what it takes for voting to pass
- [ ] Have Ata fill out the other needs here
- [ ] What are the voting options
- [ ] process for creating and forking proposals
- [ ] voting timeline

## 🤼‍♂️   Reviewer

@

**Comment by ataberkcasur** [comment]
what are the voting options

**Comment by liviade1** [comment]
Submit emoji vote to change decision making to CV

**Comment by GriffGreen** [comment]
We might want to change it to dandelion voting

**Comment by liviade1** [comment]
merging this issue with this one https://app.zenhub.com/workspaces/core-team-organization-5f1206c0362e7b000fc0161b/issues/tecommons/coordination/58
