### ISSUE TITLE
update the proposals category in the forum 

### ISSUE THREAD

**Issue by liviade1** [TECommons/coordination#266]
## 🎉 Subtasks

- [x] create sub categories for cv, signal and dv 
- [x] consider creating a category just for advice phase, then moving to the right category once is ready to be voted on 
- [ ] explain step by step - what is each sub category used for, advice process, voting times

## 🤼‍ Reviewer

@

**Comment by freedumbs00** [comment]
Closed this issue but it should be known that in order to keep topics or posts in order it requires hacking the timestamp.  So whatever topic you want first has to be the most recent.  Otherwise![Screen Shot 2021-01-25 at 4.20.32 PM.png](https://images.zenhubusercontent.com/5fb9b1cedcaf66207689f19b/80acfd9b-c1a8-4a59-aa8f-6ccff9b17878) everything new coming in will replace them.
