### ISSUE TITLE
Update the 1hive Wiki with Gardens info

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#271]
## 📋 Anything to add?

From Willjgriff in buzz 1hive disord channel

@griff I also still want to get you guys involved in contributing to the 1Hive Wiki any details you have about Gardens. The Gardens section is still empty and since you were awarded a proposal through 1Hive it would be great if you could add details about what you're building and what Gardens is. For reference: https://1hive.gitbook.io/1hive/

## ⏰ Urgency/Due Date/Blockers?

ASAP!!!

## ❓ Why is it important?

Blocker for getting funding

## 🎉 Subtasks

- [x] Find someone from Gardens to take this on (Griff does this)
- [x] Attack the Wiki (someone else)
- [ ] Griff Reviews and makes it pop!

## 🤼‍ Reviewer

@GriffGreen 

## 🔗 Work doc - inspirational links
https://1hive.gitbook.io/1hive/

**Comment by willjgriff** [comment]
Whoever's interested in working on this, please contract me directly and I'll give you write access to the Wiki. Then we can see it as you're doing and all help out if we can.

**Comment by willjgriff** [comment]
Also whoever looks into this please discuss with @lkngtn. He's written a potential structure for the section at the bottom of this document: https://hackmd.io/8D4o_FhvRyy1l7YZyD12YA and started some brainstorming on what 1Hive Gardens might look like: https://hackmd.io/eQlLWTcqRWOFDjDHvi9ncA. However, since this isn't fleshed out it would be great to have whatever is the current understanding of Gardens on the Wiki still.
