### ISSUE TITLE
Define a few legal "use cases" to make sure we have a clear solution for these worst case scenarios

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#28]
## 📋   Anything to add?

I am making shit up... so hopefully someone smarter than me can take this issue and make it better... but I am calling a legal "use case"  any scenario where someone can claim damages, with these 3 points clearly defined:

1. The scenario... What happened.
2. Who can claim damages
3. Who they can say is "at fault"

The goal here is to come up with like 10ish of these and make sure they are all covered by our legal strategy... or if they aren't admit that and warn all participants of that fact!

For example:

Alice buys into the bonding curve right after the hatch and holds the token for 6 months... During the course of those 6 months, a few projects collect funds and never deliver on their expected projects. The token has lost 20% of it's value and she believes she is entitled to damages because she blames the projects that never delivered and she blames the Community Stewards for 

## 🎉   Subtasks

- [ ] Find someone to champion this issue
- [ ] Write down 10+ legal "use cases"
- [ ] Create a new github issue for each use case to make a plan for how we should cover it

## 🤼‍♂️   Reviewer

@Santigs 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1SqBWgu1WnwbKWBC5nubhCjDwf-TjRnunhev0kWUepAU/edit?usp=sharing

**Comment by drllau** [comment]
One obvious use case (#35) is when a proposal gets accepted but poor quality (or no) deliverables.

Another is if someone is given praise and due to reasons, not executed and they sue claiming employment.

Liquidity crisis if a major trusted seeder gets hit by bus and estate wants to withdraw to pay out widow/orphans.

**Comment by drllau** [comment]
> worst case scenarios

Legal risk matrix is a combination of impact PLUS likelihood ... better to focus on the more common rather than extreme cases as then it is worthwhile spending time/resources in either mitigation or management. Legal risk exposure comes in 3 general forms:
- debt based obligations of contract
- harm based damages of tort
- equity based restitution of equity (in common-law, may not be applicable for EU civil law)

So basically you need to tally up:
1. promises/warantees that are made and enforceable
2. what duties (eg public indemnity of volunteers) imposed by law or attached to the stipulated relationship
3. things which are "unfair" or goes against conscience (like discriminating against some classes)

Once you do then you either manage, mitigate, or [migrate](https://en.wikipedia.org/wiki/Risk_management) those risks
![](https://cuttingedgepr.com/wp-content/uploads/2019/11/Risk-assessment-matrix-example.png)

**Comment by drllau** [comment]
There are also situations where TEC (entity) may wish to initate proceedings
1. some internal mis/malfeasance - breach of trust, fraud, self-dealing
2. misappropriation of collective trademarks, eg pretend to raise money but never authorised nor permissioned by TEC ... such [situation ](https://www.theblockcrypto.com/post/79061/yfi-eminence-defi-protocol-exploited) happened
3. vampire mining which perverts the original intent of the token (perhaps enclosure of commons)

**Comment by GriffGreen** [comment]
make a doodle griff

**Comment by GriffGreen** [comment]
Please feel free to submit more issues that we want to make sure to cover

**Comment by GriffGreen** [comment]
https://calendar.google.com/event?action=TEMPLATE&tmeid=MGUxMzMxMG9yNzNjb2FqOHBrbWcwZjVqbjAgNW1rZXAxYWQxajg2MGs2ZzdpN2ZyOHBscTBAZw&tmsrc=5mkep1ad1j860k6g7i7fr8plq0%40group.calendar.google.com

**Comment by GriffGreen** [comment]
Notes from our Nov17 working sesh :-D
 
https://docs.google.com/document/d/1TCxL_NOYM5dBXi5CPF9kOw1xua3p913wNFyMo9iMyZU/edit?usp=sharing

**Comment by drllau** [comment]
The soft governance putting in place a [graduated response ](https://docs.google.com/document/d/1yrEcPoOW8Q1qDE-YWWF0MhXlcvpiMk0jmdQx25nfZ6k/edit#) to bad actors. There are more serious sanctions which can result of crossing a community bottom line:

1. optional/restorative/compulsory community service
2. correct/muting/removal of prior communications on social channels
3. shaming/suspension/expulsion as member/participation
4. Monetary penalty … forced burning, transfer or lock-in of tokens
