### ISSUE TITLE
Make Forum posts for debating the Hatch parameters 

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#29]
## 🎉   Subtasks

- [x] General Thread
- [x] Hatch Goal
- [x] Hatch Return - YGG 
- [x] Hatch Time Limit 
- [x] Impact Hours Reward - YGG
- [x] Hatch Tribute
- [x] Vesting - Tonga

## 🤼‍♂️   Reviewer

@GriffGreen  

## 🔗   Work doc - inspirational links
https://forum.tecommons.org/t/test-hatch-1-rinkeby-deployment-hatch-discussion-thread/61

**Comment by Harthor** [comment]
https://docs.google.com/document/d/1dT15bbiCTCtuYhlvRQbz4QrQCaSErBugdVs8QxkorMI/edit?usp=sharing

**Comment by LinuxIsCool** [comment]
Started a repo for the cultural build analysis here:

https://github.com/TECommons/tec-cultural-tribute-exploration

**Comment by LinuxIsCool** [comment]
- [x] [Hatch Return](https://forum.tecommons.org/t/hatch-return-deep-dive/89)
- [x] [Impact Hours Reward](https://forum.tecommons.org/t/impact-hour-rewards-deep-dive/90)
