### ISSUE TITLE
Make a Graphic for and Promote the Gravity Trainings

### ISSUE THREAD

**Issue by jessicazartler** [TECommons/coordination#299]
## 📋 Anything to add?

Make a nice graphic and promote around in CS telegram, TEC General, TE General discords, 1Hive, Whaler DAO, other DAOs

## ❓ Why is it important?

Juan is offering a great value and we shout shout it wide and get others involved and will also be a bridge to bring folks to the TEC hatch

## 🎉 Subtasks

- [x] Juan draft content
- [x] Jess make graphic
- [x] Juan/Jess/others distribute in channels of other groups

## 🤼‍ Reviewer

@jessicazartler 

## 🔗 Work doc - inspirational links
https://docs.google.com/document/d/1yqLokbvhveJafMPTfljFd1DDzQ6k8NuF7qRnct4fl2E/edit#

**Comment by jessicazartler** [comment]
![Graviton Training.jpeg](https://images.zenhubusercontent.com/5bbbccb612dafc361d419ef2/867f0b74-2926-47b0-97da-acd4cfc00c41)

📣 The TEC Community is Offering Free Conflict Resolution Training! 

Discover how to flow through tensions & why non-violent communication is crucial for Commons, DAOs & communities:

📑 Learn more https://bit.ly/2Kf1APS
✍️ Sign up https://bit.ly/3sjSUsv
🎖Earn POAP badge for attending
Discord: https://discord.gg/YzC5s35

Look forward to welcoming you! 🌈
