### ISSUE TITLE
Blog: Praise Quantification Oct. 10-23

### ISSUE THREAD

**Issue by jessicazartler** [TECommons/Coordination#3]
## 🎉   Subtasks

- [x] Jess write content
- [x] Griff send screenshots for IHs
- [x] Griff/Liva edit
- [x] Stewards review
- [x] publish

## 🤼‍♂️   Reviewer

@GriffGreen @liviade1 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/19Q7Gaou9UrxN2iCYTL10VdUXbJSyzQ9Jthlst1bGChI/edit#

**Comment by jessicazartler** [comment]
https://medium.com/token-engineering-commons/test-hatch-news-praise-leader-board-oct-10-23-46c4ef397d64

**Comment by jessicazartler** [comment]
Finished :D
