### ISSUE TITLE
track stakeholders 

### ISSUE THREAD

**Issue by liviade1** [TECommons/coordination#30]
## 🎉   Subtasks

- [x] make a spreadsheet to track all stakeholders that are being contacted by the onboarding working group 
- [x] make an open call for TEC contributors to help on onboarding 
- [ ] propose a fix amount of cred they will receive if 1- they add someone to the list who has informally agreed to participate in the hatch and 2- if their lead participates in the hatch. 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
@cranders1 @liviade1 Is this issue still relevant or can we close it?

**Comment by cranders1** [comment]
Tracking stakeholders is ongoing and will continue through hatch, eventually through Hubspot.
The source cred component of this issue seems somewhat out of place to me, at least I'm not directly involved in those convos.

**Comment by tamarandom** [comment]
@cranders1 @liviade1 Cool. There seems to be no reason to then leave it in out backlog. The cred part falls under different issues related to the Source Cred launch.

Closing! ;)
