### ISSUE TITLE
New Discord /  Building out categories with pinned messages & info

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#304]
## 📋 Anything to add?

 Building out categories with pinned messages & info

## ⏰ Urgency/Due Date/Blockers?

**Due date: Jan 15, 2021**

## ❓ Why is it important?

Related to https://github.com/tecommons/coordination/issues/303

## 🎉 Subtasks

- [x] Draft channels categories
- [ ] Review and approve
- [ ] Send to @krisjpi to set up the Discord channels 

## 🤼‍ Reviewer

@jessicazartler @eduardovegap 

## 🔗 Work doc
https://docs.google.com/document/d/1Cr_GSoGaW7SfslvIMwtFvoyj1U7i1EWWvtO2Euj7_e4/edit#heading=h.bq2alzcp5km

**Comment by markoprljic** [comment]
Updated the issue with the link to the doc outlining Discord channels. I put a proposal in the doc, please review and contribute.

Thanks.

**Comment by markoprljic** [comment]
@jessicazartler Please review the draft Discord categories. They are subject of change, we can easily rename/edit/add in Discord.
The draft approval is required so that we can do the first pass and build out Discord channel structure and continue with remaining migration issues. 

Thanks!

**Comment by markoprljic** [comment]
Updated the working doc with a few more ideas/needs https://docs.google.com/document/d/1Cr_GSoGaW7SfslvIMwtFvoyj1U7i1EWWvtO2Euj7_e4/edit#heading=h.9xfi6hl05umd

**Comment by tamarandom** [comment]
Hey @jessicazartler and @markoprljic : For the part of this issue related to categories, it's all done, right? I'm attaching the screenshot of what it looks like now.  

CC @krisjpi @eduardovegap 

What are the requirements for the "pinned messages & info" ? 

![Screen Shot 2021-02-07 at 3.53.19 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/dffe4b9b-e181-49da-8171-25ec49798fd8)

**Comment by jessicazartler** [comment]
Depends how micro you want to go with tasks -- part one was categories that was me ---- now part two needs to be done
Pinned messages for each category which is Meta -- up to you, you could leave this task or make a new one

**Comment by metaverde** [comment]
[Link to pins so far.](https://docs.google.com/document/d/1HX2gr4YZiTioR41hUOIPMdztL3UGe5FpYYM7wtQODPA/edit?usp=sharing)
It's editable.
I think that's safe here?

I'll fancify my inputs as I adapt to the formats.

**Comment by markoprljic** [comment]
> [Link to pins so far.](https://docs.google.com/document/d/1HX2gr4YZiTioR41hUOIPMdztL3UGe5FpYYM7wtQODPA/edit?usp=sharing)
> It's editable.
> I think that's safe here?

Yes :)


> 
> I'll fancify my inputs as I adapt to the formats.
> Also, I will probably edit this note going forward?

Sure, let us know when you are close to done.

> 
> Not sure where to put this:
> #gardens is now #commons as a working group,
> so do we need to rename the TEC phase _commons_ to _Token Engineering Commons_?

Makes sense to me.

**Comment by metaverde** [comment]
I'm thinking we don't need a calendar _and_ an announcements channel?
The TEC google calendar is pinned on #announcements and #general channels.
The google calendar doesn't need its own channel and upcoming events should be in the #announcements channel anyway.

**Comment by markoprljic** [comment]
Yeah, I agree, let's cut the channels we. don't need. Keep just announcements IMO.

**Comment by jessicazartler** [comment]
Sounds good for channels.. I am not seeing anything in the pins doc?? Went in the new Discord and also saw it is still in progress.. if you can send me the content or let me know when it is all up and I can edit or you could ask @eduardovegap also to review content as he supported with the links/info in the forum... 

Also, is there a way to permanently display pins on channels? Right now it is only exposed as red notification and then goes away once viewed.. let us know what support you need - thank you for the hard work!

**Comment by tamarandom** [comment]
Update : Closed
