### ISSUE TITLE
Legal Onboarding Document

### ISSUE THREAD

**Issue by Santigs** [TECommons/coordination#31]
## 🎉   Subtasks

Define every “legal scenario”, each piece of the TE Commons Puzzle
- [ ] Contributors that get Impact Hours for building the TEC
- [ ] Hatchers minting TEC tokens.
- [ ] Post Hatch TEC Minting - Bonding Curve interaction and tribute.
- [ ] Funds are released through proposals.
- [ ] Proposals failing to deliver or succeeding :-D

## 🤼‍♂️   Reviewer

@Santigs
