### ISSUE TITLE
Exploring Polycentric Governance: Decision Making in the TEC

### ISSUE THREAD

**Issue by jessicazartler** [TECommons/coordination#318]
## 🎉 Subtasks

- [ ] Jess & Jess Scaffold
- [ ] Jess Write Draft
- [ ] Livia & Jeff edit/add
- [ ] Publish & Distribute

## 🤼‍ Reviewer

@liviade1 @Jeff-Emmett 

## 🔗 Work doc - inspirational links
https://docs.google.com/document/d/1yfAbB7-lKDjXXciGuHUr1vbPsTikhdMAxNFg8g1Ihac/edit

**Comment by jessicazartler** [comment]
Sprint backlog for now - other priorities onboarding video/how to become a hatcher piece

**Comment by jessicazartler** [comment]
Dup #292
