### ISSUE TITLE
Documenting how we can use the Commons Stack Association for legal protection

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#32]
## 📋   Anything to add?

The Commons Stack has done a lot of work to set up a Swiss association to protect Hatchers and Commons Builders 

## 🎉   Subtasks

- [ ] Collect the documents (work with Griff to do this)
- [ ] Read the juicy parts of the documents and skim the rest
- [ ] Define the best use of the Commons Stack in a forum post 

## 🤼‍♂️   Reviewer

@GriffGreen 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1SqBWgu1WnwbKWBC5nubhCjDwf-TjRnunhev0kWUepAU/edit?usp=sharing
https://www.canva.com/design/DAEOXnY9VGA/T9rgwhirQ9spmYyLRTPa4A/view?utm_content=DAEOXnY9VGA&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

**Comment by drllau** [comment]
So there will need to be a transition period later to spin-out of CommonStack?

**Comment by GriffGreen** [comment]
Meet with Santi... !

**Comment by tamarandom** [comment]
Posted on Forum. Done.
