### ISSUE TITLE
Investigate ANJ

### ISSUE THREAD

**Issue by Santigs** [TECommons/coordination#35]
## 🎉   Subtasks

- [x] Check the legal terms in https://convert.tecommons.org/ (fork from Aragon)
- [x] Ask Maria (Aragon Legal)  about them
- [x] Have a follow up call with Maria

## 🤼‍♂️   Reviewer

@Santigs

**Comment by drllau** [comment]
Wrt legal risks, try to find out the reason behind Aragon [litigation ](https://defirate.com/aragon-autark/)against a grantee and [strength](https://twitter.com/autarklabs/status/1263868593709539328) of contract and subsequent [obligations](https://twitter.com/licuende/status/1263845843125370880).

What was the end [result](https://twitter.com/izqui9/status/1263883803937947648) and lessons to draw?

**Comment by GriffGreen** [comment]
ANJ T&Cs https://github.com/aragon/anj.aragon.org/blob/master/public/legal/terms-general.pdf

Notes from convo with Maria: https://docs.google.com/document/d/1uNxFYjoyDv_FsLfpyroVxlSzC5NlsNHD44iJG5UP4FQ/edit?usp=sharing

**Comment by GriffGreen** [comment]
Highlights:

Hatch is protected by Commons Stack Association
- if there is a problem and this is considered a security, the Commons Stack Association will be in trouble

It is unlikely to have regulatory issues if we
- Stay small!!!
- Don’t fund operations directly out of the funds collected (no core team cut)
- Make the tokens non-transferable
- Every participant has some power in the management of the process, and none has special powers

Having a legal wrapper limits the future options the TEC… it may interfere with working with other jurisdictions 
- Our system will have to evolve, and having a legal wrapper will get in the way… but eventually it might evolve to have a legal entity if it needs.
- Better to surround it with legal entities than for it to have one itself 

Use the words deposit/withdraw, mint/burn for interacting with the bonding curve

Live by your terms and conditions. Align the intentions. Set good intentions, live up to them and if things don't work out the way you intended its ok. 
- The goal is to fund TE Public Goods, keep that theme and be single minded about it
- No need to talk much about the details of the bonding curve and how it changes the token price.

WE CANNOT DO REVENUE SHARING AGREEMENTS
- e.g. Give the money out to fund the TE Book, do not accept a revenue stream back 
- be a grant giving org focused on a public good.

Even if the TEC doesn’t have a legal personality, we can try to protect the members in the Terms
- "UNLESS OTHERWISE REQUIRED BY LAW, IN NO EVENT SHALL WE, ARAGON ONE, THE ARAGON NETWORK DAO, THE OWNERS OF OR THE CONTRIBUTORS TO ARAGON COURT, BE LIABLE IN CONTRACT OR TORT, FOR ANY CLAIM, LOSS, DAMAGE, LIABILITY, COST OR EXPENSE OF ANY KIND”

**Comment by GriffGreen** [comment]
The DAO doesn’t need to have a legal personality, it is simply a set of tools that people use to coordinate
- If you want to sue someone, this organization has no legal personality.
- This is an experiment, you are playing under your own responsibility 
- We can’t protect you...
