### ISSUE TITLE
Create a forum post to explain mission vision values voting session on token log 

### ISSUE THREAD

**Issue by liviade1** [TECommons/coordination#36]
## 🎉   Subtasks

- [ ] explain why we need the mission vision and values
- [ ] add the previous ones? 
- [ ] explain how to propose
- [ ] explain how voting on token log works 

## 🤼‍♂️   Reviewer

@liviade1 - feel free to ask me any questions! 

## 🔗   Work doc - inspirational links
- The first sessions were held in this Miro board, feel free to use it! https://miro.com/app/board/o9J_ko8MJkI=/ 
- The onboarding guide is about to be updated, but you can find the [vision, mission and values here ](https://docs.google.com/document/d/1UDnf26QQqqc77mnhn80MLCVzJU6IdvouT-OXPrIVXCg/edit#heading=h.tpx9g4b760ky)

**Comment by tamarandom** [comment]
An excellent piece!  
https://forum.tecommons.org/t/mission-vision-and-values-tokenlog-session/296
