### ISSUE TITLE
TEC Website

### ISSUE THREAD

**Issue by markoprljic** [TECommons/coordination#362]
## 📋   Anything to add?
https://tecommons.org/

## 🎉   Subtasks

- [x] Jess and Blair write content
- [x] Kay set up back end with Manu
- [x] Rosa set up wordpress instance
- [x] Marko polish design
- [x] Jess and Blair edit content
- [x] Marko and Manu work on front end design
- [x] Jess and Blair tweak layout and content
- [x] Manu finazlize front end
- [ ] Launch & promo

## 🤼‍♂️   Reviewer

@jessicazartler @bvanderlugt 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/1VOM39PVE41_GYKUbdZCZIu_xySDp60tLTXqup2-t27I/edit

**Comment by jessicazartler** [comment]
@markoprljic let us know when it's up & we can move to promote it :D Thank you so much for all your hard work!

**Comment by markoprljic** [comment]
Oh good that you reminded me. We need to deploy on our domain!

@rosamoc is this something you can do? We want to release the website 😊

**Comment by rosamoc** [comment]
@markoprljic Done!! Website online!!

**Comment by jessicazartler** [comment]
Awesome @rosamoc !!!!! AMAZING WORK!!! Thank you so much!

Just a few things @markoprljic :

1. The Discord link at the bottom is broken - change to https://discord.gg/VSD3fbCn
 2. You can delete the period at the end of the tagline, taglines don't usually have periods
 3. I would delete the Linkedin, it's not a main channel and not active, we could add it back later
 4. I don't think all the CTAs should link to the forum... I think Get Involved should like to How to Join & Contribute section of the forum so people don't have to dig -- build with us/join the mission could also link there and maybe Join the Community link's to Discord and I would take out Join the Ecosystem - or link it to our Discord
 
 Otherwise, looks great!!!! Once we address those things we can promote :D Thank you!

**Comment by rosamoc** [comment]
@jessicazartler @markoprljic Points 1, 2 and 3 done! For point 4 could you tell me exactly which URLs they are? Thank you!

**Comment by jessicazartler** [comment]
Thank you so much @rosamoc ! Sorry for taking so long to come back..

1. Can get Involved link to https://forum.tecommons.org/t/5-how-to-join-contribute/98
Build with us / Join the mission https://forum.tecommons.org/t/5-how-to-join-contribute/98
Join the Community link's to https://discord.gg/VSD3fbCn

-Delete Join the Ecosystem 

2. Can you also create a link at the bottom for 

TEC Handbook that links here https://token-engineering-commons.gitbook.io/tec-handbook/

Thank you!!!!

**Comment by markoprljic** [comment]
@jessicazartler This request will be blocked by [this issue](https://github.com/TECommons/coordination/issues/553). I'll make sure to include your suggestions in next iteration.

**Comment by jessicazartler** [comment]
k cool thanks!
