### ISSUE TITLE
Investigate PrimeDAO

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#38]
## 📋   Anything to add?

Ideally, all the the notes would be collected in this issue. 

## 🎉   Subtasks

- [x] Research their documents
- [ ] Make a list of questions
- [ ] Schedule a call with someone familiar with their legal strategy, ideally their legal lead (Griff might be able to help)
- [ ] Take notes on the call and post them in this issue
- [ ] Create lots of new issues that the legal working group need to consider that derive from this research

## 🤼‍♂️   Reviewer

@Santigs 

## 🔗   Work doc - inspirational links

**Comment by Santigs** [comment]
Ruben went over their legal structure and created this document
https://docs.google.com/document/d/1aALnBYInQHzeHa9pXRbPWr6xpXqPqnt7mZfkkQRtsmU/edit#heading=h.s353judijvqh

**Comment by GriffGreen** [comment]
Using CuraDAO's legal entity... Interesting 

Anja will have a call with luuk this week

**Comment by GriffGreen** [comment]
Ok Questions I have....

There is the Curacao entity... but that seems like the core team and it gets some amount of funds from the IDO.

Is there any KYC?

Does the DAO have a legal wrapper of some sort...?

Excited to see their Terms and Conditions.

**Comment by GriffGreen** [comment]
PrimeDAO has no formal legal structure itself, but has a foundation that is very intimately invloved. That said they  special geographic restrictions in place, and users from Cuba, Iran, Syria, North Korea, the Crimea region of Ukraine, the United States, Afghanistan, Ethiopia, Guyana, Iraq, Sudan, Venezuela, or Yemen were not permitted to participate in it's Hatch.
