### ISSUE TITLE
Start Hatcher Outreach for CS and TEC folk

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#385]
## 📋 Anything to add?

For @freedumbs00 @eduardovegap and @tamarandom  and @liviade1 ;)

- [x] Eduardo (Friday 1/29 3pm CET)
- [x] Santi (Friday 1/29 at 2pm CET)
- [x] Zep - Eduardo/Jake 
- [X] Sem - Eduardo/Jake 
- [X] Livia (Sao Paolo) Jake/Tam Wed 2/3 at 2pm CET
- [X] Metaverde  Eduardo / Tamara (Sun Feb 7, 3pm CET)
- [X] Ludo + Nikoline (Spain) Tamara/Eduardo  (Monday Feb 8 10am CET)
- [x]  Juan Carlos (Colombia) Livia / Jake
- [x] Dan (Venezuela) Livia / Tamara (Feb 10, 10pm CET)
- [X] Craig (California) Livia / Jake
- [X] Marko  Eduardo / Tamara 
- [X] Ivy  
- [X] Durgadas Tamara / ? (Sat 6pm CET)
- [x] Craig  - Jake
- [x] Jonas -  Eduardo / Tamara 
- [x] Jess -Tamara / Livia (? I didn't see name here so added myself and Livia)
- [x] Jeff Griff / Tamara

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by tamarandom** [comment]
Excellent work, all! Closing this for this Sprint. A new one will be created for next sprint!
