### ISSUE TITLE
TEC Stewards Apply for Swiss Membership (You can apply for the scholarship!) and PLEASE log bugs/other issue you find! 

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#408]
## 📋 Anything to add?

The Swiss Membership has already undergone round 1 of user testing! 
The TEC Stewards are round 2! 
After this round of user testing, we should be ready to go live. 
You help here is so important! 

- [ ] Get 450 DAI and >0.01 ETH in your Trusted Seed ETH address

- [ ] Apply on the app :  https://develop--tech-dapp.netlify.app/pay-dues  

- [ ] Important!! Find any bugs or issues you see : https://github.com/commons-stack/tech-dapp/issues/new (Including a screenshots in the issue helps the Devs a tremendous amount)

- [ ] You can apply for the scholarship first if you need to! Instructions are here : https://docs.google.com/document/d/1dtKoCi2UQXwQBopfQkFW6DWzHgDN06jsTqpssfTWtQg/edit

**Comment by Zeptimus** [comment]
@GriffGreen added this link https://develop--tech-dapp.netlify.app/pay-dues as the New link the the Swiss membership dapp.

**Comment by tamarandom** [comment]
Thanks @Zeptimus !! I just made the update in the issue body too so everyone sees it. 🙌🏽

**Comment by GriffGreen** [comment]
Thx @Zeptimus and @tamarandom
