### ISSUE TITLE
Incorporation - Judicial identity

### ISSUE THREAD

**Issue by drllau** [TECommons/coordination#43]
## 📋  Anything to add?

 New EU [rules ](https://www.mondaq.com/fin-tech/989580/proposal-of-the-eu-regulation-on-markets-in-crypto-assets-now-officially-released-the-end-of-national-crypto-asset-legal-regimes-within-the-eu-seems-near) for cryptoassets are pushing for incorporation for any issuer (#45) ... there are a number of considerations depending on the relationship of the members to the group which is nominally non-profit (financing public goods). Also how to transition from a trusted closed hatch to more distributed governance (eg crowd-funding proposals).

## 🎉   Subtasks

- [ ] is TEcommons a club, mutual, or society?
- [ ] should initial hatch be a "donation" (cf trust with members as beneficiaries) or formal investment scheme (#42)
- [ ] what is the possible options (eg non-profit, low-profit, community interest (#46), etc)
- [ ] legal relationship to praise recipients (employees, subcontractors, grantees)

## 🤼‍♂️   Reviewer

@

## 🔗   Work doc - inspirational links

dependent on #32 to get starting point
dependent on #45 to clarify post-hatch compliance

**Comment by drllau** [comment]
![Legal Entities](https://user-images.githubusercontent.com/14944510/99058942-d3b5c200-25d8-11eb-8f40-c3af7d4d1aaf.png)
This is the spectrum of legal entities ... because of the general purpose, trusts (or civil foundations) tends to sit in the middle. Mutual (and clubs) only for benefit of members whilst charity/society are more public benefit.

**Comment by tamarandom** [comment]
Closing.
