### ISSUE TITLE
Gravity Medium post - review/distribution

### ISSUE THREAD

**Issue by jessicazartler** [TECommons/coordination#438]
## ❓ Why is it important?

Get the word out about how awesome Gravity is!

## 🎉 Subtasks

- [x] Jess review/edit post
- [ ] Support Juan in posting
- [ ] Distribute - Twitter/TG/Discord community channels

## 🤼‍ Reviewer

@JuankBell @tamarandom 

## 🔗 Work doc - inspirational links
https://docs.google.com/document/d/1vsEjahySae5EHbw9HEVfSsdwhawlc7Ukm615TVvAc8k/edit#

**Comment by tamarandom** [comment]
Hey @jessicazartler ! this is all done, right? Great post @JuankBell !!

**Comment by jessicazartler** [comment]
Yes ma'ama jamma thank you!
