### ISSUE TITLE
Outreach to Hatchers in the community or new to the community 

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#439]
## 📋 Anything to add?

In the community :
- [ ] Sponnet - Tamara + Jake
- [ ] Amin - Tamara + Jake
- [ ] Fabio - Tamara + Jake 
- [ ] Merlin - Tamara + Jake
- [ ] Kris - Jake + Eduardo
- [ ] Chuy - Eduardo / Tamara **NOT IN TEC_CURATE**
- [ ] Angela - Livia + Tamara
- [ ] Sebnem - Eduardo + Juanka.
- [ ] Ygg - Jake + Eduardo

New to the community : 
Not part of the Trusted Seed Yet but very interested
decentralizedSDG
- [ ] Jorge - Juan Carlos + Livia
- [ ] Book club folk -  Livia 

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by tamarandom** [comment]
Hey @eduardovegap Everyone on the Outreach Team has their own issue assigned where they can track the people they are contacting and the "single source of truth" is the Curate. We can close this issue as it's out of date almost as soon as it was created.

**Comment by eduardovegap** [comment]
@tamarandom noted and closed.
