### ISSUE TITLE
Investigate EU new regulation

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#45]
## 📋   Anything to add?

Ideally, all the the notes would be collected in this issue. 

## 🎉   Subtasks

- [ ] Research their documents
- [ ] Take notes on these docs call and post them in this issue
- [ ] Create lots of new issues that the legal working group need to consider that derive from this research

## 🤼‍♂️   Reviewer

@Santigs 

## 🔗   Work doc - inspirational links

**Comment by GriffGreen** [comment]
- If you mine a token you don’t need a whitepaper
- If you airdrop you don’t need a whitepaper 
- NFT’s don’t need whitepaper’s 
- If the value of your token is less than 1 million or max of 150 holders in each country
- Managerial body - if you’re not incorporated you can still be compliant

**Comment by drllau** [comment]
Most pertinent aspects

1. unifies national legislation within EU, exempts existing securities or electronic money (but does to money tokens on DLT)
2. governs crypto-asset issuers **and** service providers ... presumably bonding curve as liquidity is a "service"
3. cannot offer to public or admitted to platform without a white paper by legal entity (not individual) admitted to competent home authority
4. unless exempted (<e1M, <150)  needs to comply with information provided (participants, project, rights/obligations, underlying tech, risks)
5. passport rule that those who provide crypto-asset services on a cross-border basis shall not be required to have a **physical presence** in Host Member States 
6. rules not applicable to crypto-assets (other than stablecoins) offered to the public in the EU or admitted to trading on a trading platform **before the date of entry**
7. existing services grandfathered for 18 months until new grant of authority
8. EU legal instrument therefore no national discretion

**Comment by drllau** [comment]
**Table this** as token will be issued by time law enters into force ... 18 months grace if need to recertify any embedded services.

**Comment by tamarandom** [comment]
Closing!
