### ISSUE TITLE
Investigate Community Interest Organizations

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#46]
## 📋   Anything to add?

Ideally, all the the notes would be collected in this issue. 

## 🎉   Subtasks

- [ ] Research the documents
- [ ] Take notes on them and post them in this issue
- [ ] Create lots of new issues that the legal working group need to consider that derive from this research

## 🤼‍♂️   Reviewer

@Santigs 

## 🔗   Work doc - inspirational links

**Comment by GriffGreen** [comment]
This is sort of a sub issue of #43

**Comment by drllau** [comment]
Nexus Mutual #65 article of association allows for CIC (zero-profit) to take over management of some aspects.

**Comment by drllau** [comment]
Note that CICs are available only in Northern Ireland which is **not** part of EU unless the Brexit transitional arrangements allow for it. The [distinction ](https://www.socent.ie/community-interest-companies/) with normal for-profits are
1. an asset lock, which secures those assets to be used for the benefit of the community or transferred to another organisation which also has an asset lock, such as a charity
2. community interest statement, which ensures that there are limitations on dividends paid to shareholders 
If the company is limited by guarantee and is not for profit, meaning it has an independent legal personality and limited liability but does not require funds from its members, it can become a CIC without concerns about dividend caps

**Comment by drllau** [comment]
There is no direct EU equivalent but a possible analogy is the European Cooperative Society ([SCE](https://ec.europa.eu/growth/sectors/social-economy/cooperatives/european-cooperative-society_en))

- facilitate cooperatives' cross-border and trans-national activities
- principal object is to satisfy its members' needs and not the return of capital investment
- (quadratic) weighted voting may be allowed in certain circumstances to reflect the amount of "business" done
