### ISSUE TITLE
The Great Migration --- Change ALL Comms Materials to have NEW Discord Link 

### ISSUE THREAD

**Issue by jessicazartler** [TECommons/coordination#461]
## 📋 Anything to add?

When we migrate, we need to delete all channels out of TE and leave a bridge channel to our new TEC discord with a pinned message
We also need to change all of our archive links/platform links to reflect this

## ❓ Why is it important?

So people go to the correct place

## 🎉 Subtasks

- [x] All blog posts
- [x] TE Calendar events
- [x] Social Media platforms links (Twitter/Forum/Discord/Website etc.)

## 🤼‍ Reviewer

@tamarandom

**Comment by jessicazartler** [comment]
@markoprljic maybe @cranders1 / @iviangita are willing to support with this? I can also help

**Comment by cranders1** [comment]
I can take care of all the medium posts. Just  post the proper link here :)

**Comment by markoprljic** [comment]
> I can take care of all the medium posts. Just post the proper link here :)

https://discord.gg/v32dUaGC

**Comment by iviangita** [comment]
> @markoprljic maybe @cranders1 / @iviangita are willing to support with this? I can also help

Sure, I can do this for Twitter and the calendar events

**Comment by jessicazartler** [comment]
Thank you @cranders1 @iviangita !!! Good question Ivy -- @JuankBell what is the timing looking like? We will wait for your green light (we must also let TE know I gave Angela the heads up but let me know when we will do the "migration" and delete all the old channels from TE and have just the bridge remaining

**Comment by markoprljic** [comment]
@jessicazartler can you please also sync with Kay, he actually added a bunch of bridges and wants to know whether to delete them and leave just one?

**Comment by jessicazartler** [comment]
@JuankBell is handling this -- we just discussed in Stewards -- @JuankBell can you reach out to Kay (GleeRoyale) and inform him that we are wanting to keep/bridge all of the TEC channels and talk with him? Would super appreciate it! Thank you all -- it takes a village

**Comment by geleeroyale** [comment]
Ok - saw this - will finish bridging the rest and ask if I am unsure about a particular room!

**Comment by markoprljic** [comment]
Thank you Kay.

**Comment by cranders1** [comment]
@jessicazartler @markoprljic 
Discord links updated on all Medium posts
Whoop

**Comment by jessicazartler** [comment]
Dang you're fast!! You da best THANK YOU!!!

**Comment by markoprljic** [comment]
To all who's helping with this, please make sure to generate a link from discord that does not expire. 
Here's the one I generated https://discord.gg/xEQQrt489Z

![Image 2021-02-28 at 7.15.38 am.jpg](https://images.zenhubusercontent.com/5cc090818b624e26c3734d75/dc651836-e1ec-44f0-8c33-5486e3e7d48d)

**Comment by iviangita** [comment]
Done updating the Discord links in the calendar and Twitter content :)

**Comment by markoprljic** [comment]
Thanks @iviangita 

Blog posts to be updated (and Medium profile I assume). @jessicazartler are you going to do that?

**Comment by jessicazartler** [comment]
@cranders1 already did it :D see above his comment - thank you! :D

**Comment by jessicazartler** [comment]
@markoprljic just remembered YouTube! Reopening until we confirm --- @Zeptimus @iviangita can we go through and change all the links in YouTube across the board? Or have you done this already? Thank you!

**Comment by iviangita** [comment]
@jessicazartler I’ve updated this already in the settings so the videos this week have the new link, but I haven’t updated the link in the old videos yet

**Comment by markoprljic** [comment]
@iviangita Once you do that please close the issue. Thanks.

**Comment by jessicazartler** [comment]
@markoprljic we didn't discuss @JuankBell are we going to delete working group voice channels from TE Discord as they are no longer being used and people may get confused? We could leave general and simulations since they are being used but delete TEC working groups.. What do you all think is the best flow for this?

Angela with TE said she is okay with whatever we decide.

**Comment by markoprljic** [comment]
Delete.

**Comment by tamarandom** [comment]
+1

**Comment by jessicazartler** [comment]
Done.
