### ISSUE TITLE
Increase SEO on medium? Search for TEC and TE Commons comes up only Commons Stack posts

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#48]
## 📋   Anything to add?

After talking with Rosa the workflow is following:

- Keyword list (everyone should know it and keep it in mind before writing any content).
- Optimize website
- Adapt contents (social media, blog...) to this list
- Google analytics / social media analytics

## 🎉   Subtasks

- [x] find a champion for this small task
- [x] figure out how to make google know we exist
- [x] test that it works!

## 🤼‍♂️   Reviewer

@GriffGreen

**Comment by jessicazartler** [comment]
I will ask our new contributor Rosa since she does SEO and will be helping on our website :D

**Comment by freedumbs00** [comment]
Can we assign Eduardo here too?

**Comment by jessicazartler** [comment]
Whoever takes this on can contact our contributor and Santi's friend @rosamoc
She is an SEO expert - does this for a living

**Comment by freedumbs00** [comment]
Thank you Jess!  @eduardovegap you're up.

**Comment by eduardovegap** [comment]
Hello @rosamoc, how can I reach you? :D

**Comment by rosamoc** [comment]
Hi @eduardovegap
my telegram: @rosamoc

**Comment by markoprljic** [comment]
Hi @rosamoc I'm bringing up this task as something up next after you're done with the website. Do you think you can work on this in the next 2 weeks after we close the current sprint? Let me know please. Thanks!

**Comment by rosamoc** [comment]
Hi @markoprljic after the website, next steps:
- Final keyword list
- Make the SEO of the website according to keywords

What do you mean about SEO on medium? Review the articles and modify them according to the keywords? Or explain to the person who writes the articles how SEO should be done?

**Comment by markoprljic** [comment]
What do you recommend? I'm not an expert in SEO and was hoping you to suggest whatever we need to do now and make sure we continue doing that in the future. 
Maybe a list of things that writers should be aware of when writing articles, sounds like a good idea. And also improving existing articles. 

Open to hear your suggestions and ideas :)

**Comment by rosamoc** [comment]
@markoprljic Steps of an SEO project
1. Keyword list (everyone should know it and keep it in mind before writing any content).
2. Optimize website
3. Adapt contents (social media, blog...) to this list. Yes, as you say, I can make a list of the most important things to do in each social network. 
4. Google analytics / social media analytics. 

Now we are still at point 1.

**Comment by markoprljic** [comment]
Splendid! :)

I think this issue can be turned into an Epic now.

**Comment by markoprljic** [comment]
I'm closing this issue now and creating new issues based on the list @rosamoc you pointed out above.
