### ISSUE TITLE
Discord : Add TEC Stewards to TEC Team ;)

### ISSUE THREAD

**Issue by tamarandom** [TECommons/coordination#485]
## 📋 Anything to add?

We will need to match some names to handles, perhaps. For those that are not immediately obvious, will you mention them in the comments and we will hive mind the answers. 

The TEC Stewards are : 

- [x] Soft Gov WG - Livia(liviade#1387)
- [x] Gravity WG - Juan Carlos(juankbell#7458)
- [x] Legal WG - Santi(santigs#9769)
- [x] Hatch Outreach WG - Eduardo(eduardovegap#0422)
- [x] Hatch Outreach WG - Craig(AmwFund#0979)
- [x] Parameters WG - Jake(freedumbs00#3857)
- [x] Communication WG - Marko(markop#2007)
- [x] Communication WG - Jess(JessicaZartler#2263)
- [x] Commons Swarm WG - Sem(sem 🐝#0161)
- [x] Transparency WG -  Zeptimus(Zeptimus#3359)
- [x] Transparency WG - Ivy(iviangita#3204)
- [x] 0mega WG - Sebnem (solsista#5370)
- [x] Commons Stack representative - Griff(griff#3281)
- [x] Community Stewards WG - Tamara(Tam2140#9361)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by Vyvy-vi** [comment]
The roles have been assigned. (I made an edit to the list above to reflect the changes)
What is the username for Jake? 
Moreover, are the above-assigned discord usernames correct?

**Comment by Vyvy-vi** [comment]
Moreover, should I set up Pinning permissions for all the stewards in their working groups?

**Comment by Vyvy-vi** [comment]
The roles have been assigned-!
Closing the issue :D

**Comment by tamarandom** [comment]
Nice!
