### ISSUE TITLE
SEO - Keyword list

### ISSUE THREAD

**Issue by markoprljic** [TECommons/coordination#490]
## 📋 Anything to add?

Submit the SEO keywords list.  **Everyone should know it and keep it in mind before writing any content.**

## ❓ Why is it important?

Increase SEO across channels.

## 🎉 Subtasks

- [x] Submit SEO keywords list
- [ ] Share with Stewards
- [ ] Make it accessible for content producers (writers)

## 🤼‍ Reviewer

@markoprljic

**Comment by markoprljic** [comment]
@eduardovegap or @rosamoc Can you please share the SEO keywords list you have? Thanks.

**Comment by rosamoc** [comment]
@markoprljic @eduardovegap Yes, We have the first list but I have to make an excel with the most searched words based on this first list. When I have it, I will send it to you.
Or do you need this first list that I haven't reviewed yet?

**Comment by markoprljic** [comment]
No rush, whenever you have that list ready, it's for the next sprint. 
Also, @natenatesoo will be updating articles, social media etc. based on that list.

**Comment by eduardovegap** [comment]
thanks @rosamoc <3

**Comment by rosamoc** [comment]
@markoprljic @eduardovegap I have already completed the list. The next step is to review it and complete it if necessary. It is an excel file, how do I send it to you?

**Comment by rosamoc** [comment]
@markoprljic Ok here you are.
[TEC SEO.xlsx](https://github.com/TECommons/coordination/files/6116056/TEC.SEO.xlsx)
