### ISSUE TITLE
Talk about the proposal for fixing praise quantification!

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#52]
## 📋   Anything to add?

Livia and griff get too little IH when they quantify praise :-( 

## 🎉   Subtasks

- [ ] Come up with another method that gives Praise Quantifiers more IH
- [ ] Propose it in the forum
- [ ] Vote on it on discord

## 🤼‍♂️   Reviewer

@

**Comment by JuankBell** [comment]
How about Praise quantifiers rotation. I can join to help next session.

**Comment by drllau** [comment]
see also #86

**Comment by GriffGreen** [comment]
#86
