### ISSUE TITLE
Panvala League - discuss membership application

### ISSUE THREAD

**Issue by cranders1** [TECommons/coordination#53]
## 📋   Anything to add?
Time sensitive - current round of League expansion apps due Fri 11.13
## 🎉   Subtasks

- [ ] Add to a meeting agenda
- [ ] Provide background and context for those unawares 
- [ ] Coordinate with Niran either way 

## 🤼‍♂️   Reviewer

@jessicazartler

**Comment by jessicazartler** [comment]
After discussing in the Comms Working Group, we have decided the TEC will stay under the Commons Stack Panvala League as to not double our work, and the exposure from Gitcoin Grants is where the real promotion happens. We can reconsider in the next round, so unless @cranders1 you have any other things you would like to work on in this realm, I will close this issue and we could re-open later if we decide to start our own Panvala Leauge. Please send our thanks for the offer to Niran and we are big fans of Panvala!

**Comment by cranders1** [comment]
Thnx
