### ISSUE TITLE
Refresh Social Media logos w/ new designs

### ISSUE THREAD

**Issue by jessicazartler** [TECommons/coordination#54]
## 🎉   Subtasks

- [ ] Get credntials to access all social media profiles
- [ ] Export assets from the Figma file (link below)
- [ ] Update issue when done and Close it

## 🤼‍♂️   Reviewer

@markoprljic 

## 🔗   Work doc - inspirational links
Assets for all social media profiles https://www.figma.com/file/kyXvCY9ttgQEtsLyzSnu16/TEC-Marketing?node-id=208%3A665

**Comment by drllau** [comment]
Existing [collective](https://github.com/TECommons/tec-branding-assets) trademarks. Please inform LegalWorking group when finalised #43 so can seek legal protection against fraudsters or misuse of community brand.

**Comment by freedumbs00** [comment]
Want to assign Eduardo

**Comment by markoprljic** [comment]
Eduardo?

Someone needs to provide credentials to access social media profiles.

**Comment by freedumbs00** [comment]
@jessicazartler We need the good's so Eduardo can take this on.

**Comment by markoprljic** [comment]
Assets can be found in the [TEC Marketing Figma](https://www.figma.com/file/kyXvCY9ttgQEtsLyzSnu16/TEC-Marketing?node-id=208%3A665). I updated the issue with the link to the file.

**Comment by jessicazartler** [comment]
@markoprljic the profile is awesome - anyway you could make the cover the warped universe/nft blob style? 
@eduardovegap will send you the sign in credentials via TG
