### ISSUE TITLE
Create "Join" page on the TEC website

### ISSUE THREAD

**Issue by markoprljic** [TECommons/coordination#551]
## 📋 Anything to add?

Join page to join our community. 
Show Discord, Forum, Twitter, Youtube etc. 
Use this page to onboard people to Discord

## 🎉 Subtasks

- [ ] Marko design
- [ ] Create a page in WP 
- [ ] subdomain join.tecommons.org
- [ ] Discord API integration

## 🤼‍ Reviewer

@GriffGreen 

## 🔗 Work doc - inspirational links

Related issue https://github.com/TECommons/coordination/issues/499

**Comment by GriffGreen** [comment]
Thx for jumping all over this marko!

**Comment by baartch** [comment]
I allow myself to mention here a relation to what I wrote on the other issue:
https://github.com/TECommons/coordination/issues/554#issuecomment-805072770
What seems important to me is, who does the TEC wants as new members? I would suggest to mention this explicitely on a Join page.

**Comment by markoprljic** [comment]
Thanks so much, @baartch this is great feedback. We'll definitely think about it when preparing the content for that page. Feel free to drop more suggestions and ideas here :)
