### ISSUE TITLE
Write a forum post for Principle 3. Participatory decision-making is vital

### ISSUE THREAD

**Issue by liviade1** [TECommons/coordination#58]
## 🎉   Subtasks

- [x] Host a session to talk about our options
- [x] write a forum post explaining the discussion
- [x] experiment implementing a new decision making process ( or simply transition from discord to forum and cv)
- [ ] write a few proposals to test 

## 🤼‍♂️   Reviewer

@
