### ISSUE TITLE
Onboarding lab sessions 

### ISSUE THREAD

**Issue by liviade1** [TECommons/coordination#60]
## 🎉   Subtasks

- [x] organize the weekly flows
- [x] define the topics for the next 2 weeks
- [x] pick a date and promote the calls 

## 🤼‍♂️   Reviewer

@

**Comment by liviade1** [comment]
Juan will do one to talk about conflict management
