### ISSUE TITLE
(keep closed) Recruit and promote TE Projects During Thursday Calls 

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#62]
## 📋   Anything to add?
This is the first touch of the Onboarding process in #103
https://app.zenhub.com/workspace/o/tecommons/coordination/issues/103

## 🎉   Subtasks
- [x] Put the TE Public Good Project on the Calendar
- [x] Promote the Academy on Thursday Sync
- [x] Promote the Book on Thursday Sync on the 12th

- [x] Find a TE Public Good for the Thursday Sync on the 17th
- [x] Put on calendar notes https://www.notion.so/Calendar-be8a6868a6ef4305b7521fa35a2eb9ba
- [x] Promote that TE Public Good for the Thursday Sync on the 17th

- [x] NO presenter on the 24th

- [ ] Find a TE Public Good for the Thursday Sync on Jan. 7
- [ ] Put on calendar notes https://www.notion.so/Calendar-be8a6868a6ef4305b7521fa35a2eb9ba
- [ ] Promote that  TE Public Good for the Thursday Sync on 7

## 🤼‍♂️   Reviewer

@liviade1 @eduardovegap

**Comment by jessicazartler** [comment]
@tamarandom is Wesley with Token Log going to present this Thursday? If not, let me know and we can find a project :D Thank you!

**Comment by jessicazartler** [comment]
Should I close this now that we have recurring? Thinking yes @tamarandom

**Comment by tamarandom** [comment]
Absolutely. Closing!

**Comment by freedumbs00** [comment]
I wan't to assign Eduadro to this and pass it all off to him @jessicazartler and @tamarandom

**Comment by jessicazartler** [comment]
@iviangita has offered to assist with this since she is handling agenda/recurring twitter scheduling - we just have to tell her who is presenting a few days ahead if possible

**Comment by jessicazartler** [comment]
@eduardovegap need presenter for 2/11 -- will check with Shermin to see if she is up for it but need to fill Feb.
