### ISSUE TITLE
Gitcoin Grants Rd 8: TE Commons Grant Development, Submission, Tracking

### ISSUE THREAD

**Issue by cranders1** [TECommons/coordination#66]
## 📋   Anything to add?
TEC will again be submitting a grant to Gitcoin for CLR Matching Rd 8. In Rd 7, the TEC Grant shepherded by @liviade1 was part of 3 Gitcoin Collections & received additional Panvala League matching funding as one of the top 15 projects in the Commons Stack Conviction Voting app on Aragon (links below).

Looking for a Grant Lead and possibly content contributors 🙏 

📆 Grants Rd 8 starts Dec 2nd

## 🎉   Subtasks

- [x] Find a Champion
- [x] Collaborate with @liviade1, @GriffGreen and other TEC Gitcoin Grant champions 
- [x] Submit TEC Rd 8 Grant
- [x] Tracking and contributor follow-up

## 🤼‍♂️   Reviewer

@jessicazartler @liviade1 

## 🔗   Work doc - inspirational links
[TEC GC Rd 7 Grant](https://gitcoin.co/grants/1155/token-engineering-commons)
[Token Engineering Grant Collection](https://gitcoin.co/grants/collections?collection_id=11#)
[Commons Stack Community Grants Collection](https://gitcoin.co/grants/collections?collection_id=8#)
[Token Engineering, Commons Stack & Friend Collection](https://gitcoin.co/grants/collections?collection_id=49#)
[Panvala League](https://panvala.com/)

**Comment by drllau** [comment]
Suggestion ... EU is introducing formal rules for crypto-assets, one of which is to register a white paper. However, those are usually considered marketing material with a more detailed [yellow paper](https://wikicryptocoins.com/currency/Yellow_Paper) as technical architecture and purple paper as (open) reference implementation. As a public service, to lift the standards of token design, suggest incorporating either a CadCad or equivalent agent-based simulation (NetLogo?) as part of yellow paper. In fact, can set out a model document layout (using TEcommons as example) to convince EU regulators that professional standards are achievable for fast-track regulatory approval.

Seek funds to crowd-source a model yellow paper including agent-based simulation.

**Comment by cranders1** [comment]
https://gitcoin.co/grants/1155/token-engineering-commons
