### ISSUE TITLE
Building the Example Spec for the Community to fork and propose Params

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/coordination#70]
## 📋 Anything to add?

This will be a big undertaking, but the skeleton to flesh out is here: https://github.com/aragon/network/blob/master/implementation-spec.md

We just need to list out all the Apps we are using for the TEC deployment and take the parameters that we end up deciding on and put them all together in that format.

## ⏰ Urgency/Due Date/Blockers?

Blocked until we make our first full test rehearsal... likely late November.
 
Will be used to finalize the parameters. Final product is due in mid/late December but we want to fully specify the 1st full test deployment. 

## ❓ Why is it important?

This is the final document that informs everyone about how the DAO is set up. This is ideally the easy to access single source of truth of what is going in the DAO

## 🎉 Subtasks

- [x] Find a Champion
- [x] Describe the 1st full test deployment. 
- [ ] Revise these next steps and make issues for them
- [ ] Get feedback from the forum on all the test deployments and put your favorite parameters into the spec
- [ ] Propose the parameters into the forum
- [ ] Encourage others to fork your spec and propose alternative parameters in the forum
- [ ] When a decision process chooses a winner, publish the final parameters in github as the launch spec.

## 🤼‍ Reviewer

@GriffGreen

**Comment by freedumbs00** [comment]
https://docs.google.com/document/d/1v8rCByLYQrpyaLRXW5v0ZSPD5gecu-G1B99FMrcnSOw/edit#heading=h.qtshygpcc9p9

Completed but waiting on review from @sembrestels

**Comment by freedumbs00** [comment]
https://hackmd.io/UYQ_u-AIRbGnVqc79EV3ZA.  That's the spec
