### ISSUE TITLE
Content Piece Blog or Forum: What kinds of proposals/projects we would like to fund

### ISSUE THREAD

**Issue by jessicazartler** [TECommons/coordination#74]
## 🎉 Subtasks

- [x] Jess gather feedback from stakeholder intvws from Jonass
- [x] Jess write Forum / blog post
- [ ] Griff/Livia/stewards edit
- [ ] Publish
- [ ] Distribute

## 🤼‍ Reviewer

@GriffGreen @liviade1

**Comment by drllau** [comment]
Try not to overlap with existing gitcoin or narrow (ie small community) projects

**Comment by jessicazartler** [comment]
Sent to Stewards for feedback
https://docs.google.com/document/d/1JbJvBWRvZiD1rFFmw_D4nwZdgcBbm5n2xzgwYsHaWmI/edit?usp=sharing

**Comment by tamarandom** [comment]
🙌🏼  Excellent, @jessicazartler 🙌🏼   

https://forum.tecommons.org/t/tec-funding-proposals-what-kinds-of-projects-should-apply/191
