### ISSUE TITLE
Create / revise onboarding documentation library

### ISSUE THREAD

**Issue by cranders1** [TECommons/coordination#77]
## 📋 Anything to add?

Develop one-stop shop for all onboarding documentation
Current library spread across platforms (Wiki, YouTube, Forum)
Primary: [https://www.notion.so/Resources-2dff0f439c0a4ce1afe0ec468c36a9d6](https://www.notion.so/Resources-2dff0f439c0a4ce1afe0ec468c36a9d6
)
[Onboarding and Resources Guide to the TEC](https://docs.google.com/document/d/1UDnf26QQqqc77mnhn80MLCVzJU6IdvouT-OXPrIVXCg/edit?usp=sharing)
## ⏰ Urgency/Due Date/Blockers?

**URGENCY**: HIGH
**DUE DATE**: Nov 26 (sooner the better)
**BLOCKERS:** Path forward undetermined. 11/16 & 17 work session to crystalize.
                   : Legal determinations

## ❓ Why is it important?

Integral to guide potential builders and hatchers through an intuitive and educational process; ultimate TEC success

## 🎉 Subtasks

- [x] Onboarding Journey work session 
- [x] Decide appropriate platforms / strategies
- [ ] Collate and deploy all relevant docs and information sources

## 🤼‍ Reviewer

@liviade1 

## 🔗 Work doc - inspirational links
[TEC Wiki](https://www.notion.so/TEC-Wiki-0460a521d72940ecad401ae1571b87fb)
[Onboarding and Resources Guide to the TEC](https://docs.google.com/document/d/1UDnf26QQqqc77mnhn80MLCVzJU6IdvouT-OXPrIVXCg/edit?usp=sharing)
[PrimeDAO Docs](https://docs.primedao.io/)
[xDai Chain](https://www.xdaichain.com/)

**Comment by drllau** [comment]
The common stacks verein [articles of association](https://drive.google.com/file/d/1CEckMBQvHQ4eWipbGhi3UZm-JRizju1Q/view) and as this point [terms and condition](https://docs.google.com/document/d/1j1nbXPX8w2kQ-726FMGQWgagfiBH3eyxdcL1IJHV93s/edit?usp=sharing)

**Comment by tamarandom** [comment]
Closed!
