### ISSUE TITLE
Develop new template to become TEC Builders / submit proposal 

### ISSUE THREAD

**Issue by cranders1** [TECommons/coordination#78]
## 📋 Anything to add?

Develop new template for TEC proposal submission.

## ⏰ Urgency/Due Date/Blockers?
**URGENCY**: High
**DUE DATE**: Nov 26 or ASAP
**BLOCKERS**: Finalized reqs
: Legal?

## ❓ Why is it important?

Establishing consistent TEC proposal and builder onboarding requirements 

## 🎉 Subtasks

- [ ] Review existing TEC Forum proposal template
- [ ] Sync with other WG stewards to incorporate inputs
- [ ] Develop standardized TEC Builder requirements template

## 🤼‍ Reviewer

@jessicazartler @GriffGreen 

## 🔗 Work doc - inspirational links
[TEC Onboarding and Resources Guide](https://docs.google.com/document/d/1UDnf26QQqqc77mnhn80MLCVzJU6IdvouT-OXPrIVXCg/edit?usp=sharing)
[TEC Forum Proposal Template ](https://forum.tecommons.org/t/test-2-conviction-voting-signaling-proposal/47)

**Comment by jessicazartler** [comment]
Duplicate #79
