### ISSUE TITLE
Collaborate with Legal WG on DAO Investigations

### ISSUE THREAD

**Issue by cranders1** [TECommons/coordination#80]
## 📋 Anything to add?

The Legal WG is putting excellent work into DAO legal investigations and dao2dao collaborations / partnerships with several active research issues (#38 , #39 , #47 , #49 ). Onboarding WG needs to track their progress and incorporate results into relevant Onboarding documents and procedures.  

## ⏰ Urgency/Due Date/Blockers?

**URGENCY**: Low
**DUE DATE**: Ongoing
**BLOCKERS**: Legal determinations

## 🎉 Subtasks

- [ ] Contact LWG Steward @Santigs for insights about most efficient collaboration method 
- [ ] Sync with various members conducting research on individual DAOS
- [ ] Incorporate findings into relevant docs

## 🤼‍ Reviewer

@Santigs 

## 🔗 Work doc - inspirational links
[Legal WG Project Board](https://github.com/TECommons/coordination/projects/1)
